restart-times: 0
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
jobs: 200
latency-wait: 60000000
use-envmodules: false
use-singularity: true
rerun-incomplete: false
printshellcmds: true
