restart-times: 0
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
jobs : 100
latency-wait: 60
use-envmodules: true
use-singularity: false
rerun-incomplete: true
printshellcmds: true
